### ISSUE TITLE
splitext can't split the path

### ISSUE THREAD

**Issue by TheAifam5** [RadekSimkanic/Linux-SDM-Downloader#15]
``python ./main.py xxxxxxxxxx.sdx`` will not work.
``python ./main.py ./xxxxxxxxxx.sdx`` works.

Logs:
```
Info: Parsing page
Traceback (most recent call last):
  File "./main.py", line 492, in <module>
    main()
  File "./main.py", line 46, in main
    d.execute()
  File "./main.py", line 125, in execute
    if self._downloadFiles() == False:
  File "./main.py", line 250, in _downloadFiles
    self._setupDLDir()
  File "./main.py", line 380, in _setupDLDir
    os.chdir(os.path.dirname(self._sdxFile))
FileNotFoundError: [Errno 2] No such file or directory: ''
```

**Comment by RadekSimkanic** [comment]
Is there still a problem? What is your operating system? Which version of Python do you use? Please actualize source code and put here output from terminal.

**Comment by TheAifam5** [comment]
No, actually works.

Python3.
ArchLinux.
