### ISSUE TITLE
 Entity 'nbsp' not defined  manjaro 4.10.1-1 python2

### ISSUE THREAD

**Issue by jonasbrami** [RadekSimkanic/Linux-SDM-Downloader#16]
Info: Opening SDX file
Info: Parsing URL
Info: Downloading main page
Info: Parsing done!
Choose file:
	Windows 7 Professional
	#1 | en_windows_7_professional_with_sp1_x86_dvd_u_677056.01.sdc
	#2 | en_windows_7_professional_with_sp1_x64_dvd_u_676939.01.sdc
Please select file via number 1 - 2: 1
Info: Creating URL
Info: Downloading page contains download link
Info: Parsing page
Traceback (most recent call last):
  File "main.py", line 492, in <module>
    main()
  File "main.py", line 46, in main
    d.execute()
  File "main.py", line 125, in execute
    if self._downloadFiles() == False:
  File "main.py", line 222, in _downloadFiles
    parse = etree.XML(html)
  File "src/lxml/lxml.etree.pyx", line 3192, in lxml.etree.XML (src/lxml/lxml.etree.c:78763)
  File "src/lxml/parser.pxi", line 1848, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:118341)
  File "src/lxml/parser.pxi", line 1736, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:117021)
  File "src/lxml/parser.pxi", line 1102, in lxml.etree._BaseParser._parseDoc (src/lxml/lxml.etree.c:111265)
  File "src/lxml/parser.pxi", line 595, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:105109)
  File "src/lxml/parser.pxi", line 706, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:106817)
  File "src/lxml/parser.pxi", line 635, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:105671)
  File "<string>", line 33
lxml.etree.XMLSyntaxError: Entity 'nbsp' not defined, line 33, column 103
[mrhoumous@mrhoumous-pc Linux-SDM-Downloader]$ ^C
[mrhoumous@mrhoumous-pc Linux-SDM-Downloader]$ ^C
[mrhoumous@mrhoumous-pc Linux-SDM-Downloader]$ python main.py 100534278518.sdx
Info: Opening SDX file
Info: Parsing URL
Info: Downloading main page
Info: Parsing done!
Choose file:
	Windows 7 Professional
	#1 | en_windows_7_professional_with_sp1_x86_dvd_u_677056.01.sdc
	#2 | en_windows_7_professional_with_sp1_x64_dvd_u_676939.01.sdc
Please select file via number 1 - 2: 2
Info: Creating URL
Info: Downloading page contains download link
Info: Parsing page
Traceback (most recent call last):
  File "main.py", line 492, in <module>
    main()
  File "main.py", line 46, in main
    d.execute()
  File "main.py", line 125, in execute
    if self._downloadFiles() == False:
  File "main.py", line 222, in _downloadFiles
    parse = etree.XML(html)
  File "src/lxml/lxml.etree.pyx", line 3192, in lxml.etree.XML (src/lxml/lxml.etree.c:78763)
  File "src/lxml/parser.pxi", line 1848, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:118341)
  File "src/lxml/parser.pxi", line 1736, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:117021)
  File "src/lxml/parser.pxi", line 1102, in lxml.etree._BaseParser._parseDoc (src/lxml/lxml.etree.c:111265)
  File "src/lxml/parser.pxi", line 595, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:105109)
  File "src/lxml/parser.pxi", line 706, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:106817)
  File "src/lxml/parser.pxi", line 635, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:105671)
  File "<string>", line 33
lxml.etree.XMLSyntaxError: Entity 'nbsp' not defined, line 33, column 103

**Comment by Flowelfox** [comment]
I have this problem too, kali linux 2.0 x64, python2.7.12+

**Comment by RadekSimkanic** [comment]
Could you get me send yours sdx file?

**Comment by jonasbrami** [comment]
http://rgho.st/7xm2TqHy5

**Comment by Flowelfox** [comment]
http://rgho.st/7vftXsQMR

**Comment by mchelpa** [comment]
I have same problem, seems like there is an issue with windows 7 sdx

Elementary OS 0.4 Loki
http://rgho.st/7JN58rgMb

**Comment by AWegner1** [comment]
same for me too...
Windows 7 Professional
Extracted this one as the response when trying to download the XML file:
[test.txt](https://github.com/RadekSimkanic/Linux-SDM-Downloader/files/923594/test.txt)
Seems like M$ changed something bigger...

**Comment by gcfabri** [comment]
same issue using Elementary OS 0.4 Loki and trying to download Windows 7 Professional sdx.

**Comment by PolynomialDivision** [comment]
Same issue with Xubuntu 16.04

**Comment by thtrieu** [comment]
Same on ubuntu 16.04 LTS, SDX from Windows 7 Professional download.

**Comment by tpimh** [comment]
I'm having the same issue with the same download. I downloaded the sdc files manually and glued them together, but I can't find the key to decrypt them, `edv` value is empty or missing.

**Comment by RadekSimkanic** [comment]
Maybe it's fixed! :) Try it.

**Comment by tpimh** [comment]
It doesn't crash anymore, but for some reason it only downloads the first part and the file is named `_`. Here is what it printed to me:
```
Info: Opening SDX file
Info: Parsing URL
Info: Downloading main page
Info: Parsing done!
Choose file:
	Windows 7 Professional
	#1 | en_windows_7_professional_with_sp1_x86_dvd_u_677056.01.sdc
	#2 | en_windows_7_professional_with_sp1_x64_dvd_u_676939.01.sdc
Please select file via number 1 - 2: 2
Info: Creating URL
Info: Ready to download immediately.
Info: Testing download URL: http://software.dreamspark.com/dreamspark/ENGLISH/en_windows_7_professional_with_sp1_x64_dvd_u_676939.01.sdc
Downloading: en_windows_7_professional_with_sp1_x64_dvd_u_676939.01.sdc Bytes: 2147483647
Info: Gluing...0.00%]
 SDC file is DONE! 
```

**Comment by RadekSimkanic** [comment]
Send me please your SDX file.

**Comment by tpimh** [comment]
Here you are: [100545585215.sdx](https://github.com/RadekSimkanic/Linux-SDM-Downloader/files/1017367/100545585215.sdx.txt)

**Comment by RadekSimkanic** [comment]
tpimh: fixed, try again please.

**Comment by tpimh** [comment]
Now the filename is correct, but the second part (`en_windows_7_professional_with_sp1_x64_dvd_u_676939.02.sdc`) is never downloaded and there is no key.
```
Info: Opening SDX file
Info: Parsing URL
http://e5.onthehub.com/WebStore/Account/SdmAuthorize.aspx?o=5a87cd53-a039-e711-80ef-000d3af41938&ws=7d7693c6-a672-e011-971f-0030487d8897&uid=bfd0bf88-ae43-e411-9403-b8ca3a5db7a1&dfc=1
Info: Downloading main page
Info: Parsing done!
Choose file:
	Windows 7 Professional
	#1 | en_windows_7_professional_with_sp1_x86_dvd_u_677056.01.sdc
	#2 | en_windows_7_professional_with_sp1_x64_dvd_u_676939.01.sdc
Please select file via number 1 - 2: 2
Info: Creating URL
Info: Ready to download immediately.
Info: Testing download URL: http://software.dreamspark.com/dreamspark/ENGLISH/en_windows_7_professional_with_sp1_x64_dvd_u_676939.01.sdc
Downloading: en_windows_7_professional_with_sp1_x64_dvd_u_676939.01.sdc Bytes: 2147483647
Info: Glue is not needed
 SDC file is DONE! 
```

**Comment by RadekSimkanic** [comment]
wow this have two (more) parts. I look at it. I don't found key, respectively is empty.

**Comment by tpimh** [comment]
Yes, I was also looking for edv field and found nothing. Perhaps it should be investigated how the original downloader obtains the key.
