### ISSUE TITLE
Error downloading an iso

### ISSUE THREAD

**Issue by ofou** [RadekSimkanic/Linux-SDM-Downloader#17]
I was trying to download an iso but unfortunately I couldn't. The program gave me this error.

`Info: Opening SDX file
Info: Parsing URL
Info: Downloading main page
Info: Parsing done!
Choose file:
	Windows 7 Professional
	#1 | es_windows_7_professional_with_sp1_x86_dvd_u_677069.01.sdc
	#2 | es_windows_7_professional_with_sp1_x64_dvd_u_676947.01.sdc
Please select file via number 1 - 2: 2
Info: Creating URL
Info: Downloading page contains download link
Info: Parsing page
Traceback (most recent call last):
  File "main.py", line 492, in <module>
    main()
  File "main.py", line 46, in main
    d.execute()
  File "main.py", line 125, in execute
    if self._downloadFiles() == False:
  File "main.py", line 222, in _downloadFiles
    parse = etree.XML(html)
  File "src/lxml/lxml.etree.pyx", line 3192, in lxml.etree.XML (src/lxml/lxml.etree.c:78763)
  File "src/lxml/parser.pxi", line 1848, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:118341)
  File "src/lxml/parser.pxi", line 1736, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:117021)
  File "src/lxml/parser.pxi", line 1102, in lxml.etree._BaseParser._parseDoc (src/lxml/lxml.etree.c:111265)
  File "src/lxml/parser.pxi", line 595, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:105109)
  File "src/lxml/parser.pxi", line 706, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:106817)
  File "src/lxml/parser.pxi", line 635, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:105671)
  File "<string>", line 33
lxml.etree.XMLSyntaxError: Entity 'nbsp' not defined, line 33, column 103
`
What can I do to solve it?

**Comment by RadekSimkanic** [comment]
Maybe it's fixed! :) Try it.

**Comment by ofou** [comment]
I tried again and it gave the same error. :cry:  I'm using Ubuntu 17.04 Zesty Zapus.

`peel40@peel40-pc:~/Downloads/Linux-SDM-Downloader$ python  main.py 100409952613.sdx 
Info: Opening SDX file
Info: Parsing URL
Info: Downloading main page
Info: Parsing done!
Choose file:
	Windows 7 Professional
	#1 | es_windows_7_professional_with_sp1_x86_dvd_u_677069.01.sdc
	#2 | es_windows_7_professional_with_sp1_x64_dvd_u_676947.01.sdc
Please select file via number 1 - 2: 2
Info: Creating URL
Info: Downloading page contains download link
Info: Parsing page
Traceback (most recent call last):
  File "main.py", line 492, in <module>
    main()
  File "main.py", line 46, in main
    d.execute()
  File "main.py", line 125, in execute
    if self._downloadFiles() == False:
  File "main.py", line 222, in _downloadFiles
    parse = etree.XML(html)
  File "src/lxml/lxml.etree.pyx", line 3192, in lxml.etree.XML (src/lxml/lxml.etree.c:78763)
  File "src/lxml/parser.pxi", line 1848, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:118341)
  File "src/lxml/parser.pxi", line 1736, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:117021)
  File "src/lxml/parser.pxi", line 1102, in lxml.etree._BaseParser._parseDoc (src/lxml/lxml.etree.c:111265)
  File "src/lxml/parser.pxi", line 595, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:105109)
  File "src/lxml/parser.pxi", line 706, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:106817)
  File "src/lxml/parser.pxi", line 635, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:105671)
  File "<string>", line 33
lxml.etree.XMLSyntaxError: Entity 'nbsp' not defined, line 33, column 103
`

**Comment by RadekSimkanic** [comment]
Did you actualize the script? Try again after actualize. When is still wrong send me please your sdx file

**Comment by ofou** [comment]
Fixed and working! Thank you very much :+1:
