### ISSUE TITLE
Crash on download complete

### ISSUE THREAD

**Issue by robbert229** [RadekSimkanic/Linux-SDM-Downloader#3]
When it finishes downloading and starts reassembling the parts it crashes.

```
Info: Downloaded.
Traceback (most recent call last):
  File "main.py", line 401, in <module>
    main()
  File "main.py", line 36, in main
    d.execute()
  File "main.py", line 79, in execute
    self._glue()
  File "main.py", line 277, in _glue
    message("Gluing...")
TypeError: message() takes exactly 2 arguments (1 given)
```

**Comment by robbert229** [comment]
PR #4 fixes it
